### ISSUE TITLE
Confluence version 6.1 is not supported by the cookbook

### ISSUE THREAD

**Issue by anbuela** [sous-chefs/confluence#182]
Hi team,

While upgrading confluence from cookbook using custom jason.
 we are getting this error.
[2019-09-10T07:03:57+00:00] INFO: Processing chef_gem[aws-sdk-core] action install (alb_support::attach_to_alb line 18)
[2019-09-10T07:03:57+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/data/confluence/confluence
[2019-09-10T07:03:57+00:00] ERROR: Failed to load data bag item: "confluence" "confluence"
[2019-09-10T07:03:57+00:00] INFO: No confluence data bag found
 
================================================================================
Recipe Compile Error in /var/chef/runs/44aeed95-ac3e-477e-a095-ccc1ce83b8d5/local-mode-cache/cache/cookbooks/confluence/recipes/default.rb
================================================================================
 
RuntimeError
------------
Confluence version 6.1 is not supported by the cookbook
 
Cookbook Trace:
---------------
/var/chef/runs/44aeed95-ac3e-477e-a095-ccc1ce83b8d5/local-mode-cache/cache/cookbooks/confluence/libraries/helpers.rb:131:in `confluence_artifact_checksum'
/var/chef/runs/44aeed95-ac3e-477e-a095-ccc1ce83b8d5/local-mode-cache/cache/cookbooks/confluence/recipes/linux_installer.rb:49:in `block in from_file'
/var/chef/runs/44aeed95-ac3e-477e-a095-ccc1ce83b8d5/local-mode-cache/cache/cookbooks/confluence/recipes/linux_installer.rb:47:in `from_file'
/var/chef/runs/44aeed95-ac3e-477e-a095-ccc1ce83b8d5/local-mode-cache/cache/cookbooks/confluence/recipes/default.rb:23:in `from_file'
 
Relevant File Content:
----------------------
/var/chef/runs/44aeed95-ac3e-477e-a095-ccc1ce83b8d5/local-mode-cache/cache/cookbooks/confluence/libraries/helpers.rb:
 
124:      # Returns SHA256 checksum of specific Confluence artifact
125:      def confluence_artifact_checksum
126:        return node['confluence']['checksum'] unless node['confluence']['checksum'].nil?
127:  
128:        version = node['confluence']['version']
129:        sums = confluence_checksum_map[version]
130:  
131>>       raise "Confluence version #{version} is not supported by the cookbook" unless sums
132:  
133:        case node['confluence']['install_type']
134:        when 'installer' then sums[confluence_arch]
135:        when 'standalone' then sums['tar']
136:        end
137:      end
138:  
139:      def confluence_arch
140:        (node['kernel']['machine'] == 'x86_64') ? 'x64' : 'x32'
 
Platform:
---------

**Comment by damacus** [comment]
Fixed via #273
