### ISSUE TITLE
Installation fails when java installation not included

### ISSUE THREAD

**Issue by esciara** [sous-chefs/confluence#7]
On 7ed6eef7d6ad859ec13cc55d527316dbbd7f1bcf when trying the following test suite in test-kitchen:

```
- name: confluence-installer-mysql-no-java
  run_list:
  - recipe[confluence]
  attributes:
    mysql:
      server_root_password: iloverandompasswordsbutthiswilldo
      server_repl_password: iloverandompasswordsbutthiswilldo
      server_debian_password: iloverandompasswordsbutthiswilldo
```

by running `bundle exec kitchen test -no-java-ubuntu-1204`, it fails with the following log:

``````
-----> Cleaning up any prior instances of <confluence-installer-mysql-no-java-ubuntu-1204>
-----> Destroying <confluence-installer-mysql-no-java-ubuntu-1204>...
Finished destroying <confluence-installer-mysql-no-java-ubuntu-1204> (0m0.00s).
-----> Testing <confluence-installer-mysql-no-java-ubuntu-1204>
-----> Creating <confluence-installer-mysql-no-java-ubuntu-1204>...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'opscode-ubuntu-12.04'...

[KProgress: 10%
[KProgress: 20%
[KProgress: 40%
[KProgress: 70%
[KProgress: 80%
[KProgress: 90%
[K==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: confluence-installer-mysql-no-java-ubuntu-1204_default_1397241356947_69573
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
Vagrant instance <confluence-installer-mysql-no-java-ubuntu-1204> created.
Finished creating <confluence-installer-mysql-no-java-ubuntu-1204> (0m32.44s).
-----> Converging <confluence-installer-mysql-no-java-ubuntu-1204>...
Preparing files for transfer
Resolving cookbook dependencies with Berkshelf 2.0.14...
Removing non-cookbook files before transfer
-----> Installing Chef Omnibus (latest)
downloading https://www.getchef.com/chef/install.sh
  to file /tmp/install.sh
trying wget...

Downloading Chef  for ubuntu...
downloading https://www.getchef.com/chef/metadata?v=&prerelease=false&p=ubuntu&pv=12.04&m=x86_64
  to file /tmp/install.sh.1149/metadata.txt
trying wget...
url https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef_11.12.2-1_amd64.deb
md5 cedd8a2df60a706e51f58adf8441971b
sha256  af53e7ef602be6228dcbf68298e2613d3f37eb061975992abc6cd2d318e4a0c0
downloaded metadata file looks valid...
downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef_11.12.2-1_amd64.deb
  to file /tmp/install.sh.1149/chef_11.12.2-1_amd64.deb
trying wget...
Comparing checksum with sha256sum...
Installing Chef 
installing with dpkg...
Selecting previously unselected package chef.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 56035 files and directories currently installed.)
Unpacking chef (from .../chef_11.12.2-1_amd64.deb) ...
Setting up chef (11.12.2-1) ...
Thank you for installing Chef!
Transfering files to <confluence-installer-mysql-no-java-ubuntu-1204>
[2014-04-11T18:36:55+00:00] INFO: Forking chef instance to converge...
[2014-04-11T18:36:55+00:00] WARN: 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
SSL validation of HTTPS requests is disabled. HTTPS connections are still
encrypted, but chef is not able to detect forged replies or man in the middle
attacks.

To fix this issue add an entry like this to your configuration file:

\```
  # Verify all HTTPS connections (recommended)
  ssl_verify_mode :verify_peer

  # OR, Verify only connections to chef-server
  verify_api_cert true
\```

To check your SSL configuration, or troubleshoot errors, you can use the
`knife ssl check` command like so:

\```
  knife ssl check -c /tmp/kitchen/solo.rb
\```

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 

Starting Chef Client, version 11.12.2[0m
[2014-04-11T18:36:55+00:00] INFO: *** Chef 11.12.2 ***
[2014-04-11T18:36:55+00:00] INFO: Chef-client pid: 1231
[2014-04-11T18:36:57+00:00] INFO: Setting the run_list to ["recipe[confluence]"] from CLI options
[2014-04-11T18:36:57+00:00] INFO: Run List is [recipe[confluence]]
[2014-04-11T18:36:57+00:00] INFO: Run List expands to [confluence]
[2014-04-11T18:36:57+00:00] INFO: Starting Chef Run for confluence-installer-mysql-no-java-ubuntu-1204
[2014-04-11T18:36:57+00:00] INFO: Running start handlers
[2014-04-11T18:36:57+00:00] INFO: Start handlers complete.
Compiling Cookbooks...[0m
[2014-04-11T18:36:58+00:00] INFO: WindowsPackage light-weight resource already initialized -- overriding!
[2014-04-11T18:36:58+00:00] INFO: No confluence data bag found
[2014-04-11T18:36:58+00:00] INFO: No confluence data bag found
[2014-04-11T18:36:58+00:00] WARN: Cloning resource attributes for directory[/var/lib/mysql] from prior resource (CHEF-3694)
[2014-04-11T18:36:58+00:00] WARN: Previous directory[/var/lib/mysql]: /tmp/kitchen/cookbooks/mysql/recipes/_server_debian.rb:34:in `block in from_file'
[2014-04-11T18:36:58+00:00] WARN: Current  directory[/var/lib/mysql]: /tmp/kitchen/cookbooks/mysql/recipes/_server_debian.rb:78:in `from_file'
Recipe: build-essential::debian[0m
  * execute[apt-get-update-build-essentials] action run[0m[2014-04-11T18:36:58+00:00] INFO: Processing execute[apt-get-update-build-essentials] action run (build-essential::debian line 22)
[2014-04-11T18:37:08+00:00] INFO: execute[apt-get-update-build-essentials] ran successfully
[32m
    - execute apt-get update[0m
[0m
  * package[autoconf] action install[0m[2014-04-11T18:37:08+00:00] INFO: Processing package[autoconf] action install (build-essential::debian line 40)
[32m
    - install version 2.68-1ubuntu2 of package autoconf[0m
[0m
  * package[binutils-doc] action install[0m[2014-04-11T18:37:12+00:00] INFO: Processing package[binutils-doc] action install (build-essential::debian line 40)
[32m
    - install version 2.22-6ubuntu1.1 of package binutils-doc[0m
[0m
  * package[bison] action install[0m[2014-04-11T18:37:15+00:00] INFO: Processing package[bison] action install (build-essential::debian line 40)
[32m
    - install version 1:2.5.dfsg-2.1 of package bison[0m
[0m
  * package[build-essential] action install[0m[2014-04-11T18:37:17+00:00] INFO: Processing package[build-essential] action install (build-essential::debian line 40)
 (up to date)[0m
  * package[flex] action install[0m[2014-04-11T18:37:17+00:00] INFO: Processing package[flex] action install (build-essential::debian line 40)
[32m
    - install version 2.5.35-10ubuntu3 of package flex[0m
[0m
Recipe: mysql::client[0m
  * package[mysql-client] action install[0m[2014-04-11T18:37:19+00:00] INFO: Processing package[mysql-client] action install (mysql::client line 47)
[32m
    - install version 5.5.35-0ubuntu0.12.04.2 of package mysql-client[0m
[0m
  * package[libmysqlclient-dev] action install[0m[2014-04-11T18:37:36+00:00] INFO: Processing package[libmysqlclient-dev] action install (mysql::client line 47)
[32m
    - install version 5.5.35-0ubuntu0.12.04.2 of package libmysqlclient-dev[0m
[0m
Recipe: mysql::ruby[0m
  * chef_gem[mysql] action install[0m[2014-04-11T18:37:40+00:00] INFO: Processing chef_gem[mysql] action install (mysql::ruby line 47)
[32m
    - install version 2.9.1 of package mysql[0m
[0m
[2014-04-11T18:37:55+00:00] INFO: No confluence data bag found
[0m
================================================================================[0m
[31mRecipe Compile Error in /tmp/kitchen/cookbooks/confluence/recipes/default.rb[0m
================================================================================[0m

[0m
NoMethodError[0m
-------------[0m
undefined method `[]' for nil:NilClass[0m

[0m
Cookbook Trace:[0m
---------------[0m
  /tmp/kitchen/cookbooks/confluence/recipes/linux_installer.rb:44:in `block in from_file'
  /tmp/kitchen/cookbooks/confluence/recipes/linux_installer.rb:42:in `from_file'
  /tmp/kitchen/cookbooks/confluence/recipes/default.rb:25:in `from_file'[0m

[0m
Relevant File Content:[0m
----------------------[0m
/tmp/kitchen/cookbooks/confluence/recipes/linux_installer.rb:

 37:    cwd Chef::Config[:file_cache_path]
 38:    command "./atlassian-confluence-#{node['confluence']['version']}-#{node['confluence']['arch']}.bin -q -varfile atlassian-confluence-response.varfile"
 39:    creates node['confluence']['install_path']
 40:  end
 41:  
 42:  execute 'Generating Self-Signed Java Keystore' do
 43:    command <<-COMMAND
 44>>     #{node['java']['java_home']}/bin/keytool -genkey \
 45:        -alias #{settings['tomcat']['keyAlias']} \
 46:        -keyalg RSA \
 47:        -dname 'CN=#{node['fqdn']}, OU=Example, O=Example, L=Example, ST=Example, C=US' \
 48:        -keypass #{settings['tomcat']['keystorePass']} \
 49:        -storepass #{settings['tomcat']['keystorePass']} \
 50:        -keystore #{settings['tomcat']['keystoreFile']}
 51:      chown #{node['confluence']['user']}:#{node['confluence']['user']} #{settings['tomcat']['keystoreFile']}
 52:    COMMAND
 53:    creates settings['tomcat']['keystoreFile']
[0m

[0m

Running handlers:[0m
[2014-04-11T18:37:55+00:00] ERROR: Running exception handlers
Running handlers complete
[0m
[2014-04-11T18:37:55+00:00] ERROR: Exception handlers complete
[2014-04-11T18:37:55+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
Chef Client failed. 8 resources updated in 59.616297425 seconds[0m
[2014-04-11T18:37:55+00:00] ERROR: undefined method `[]' for nil:NilClass
[2014-04-11T18:37:55+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Converge failed on instance <confluence-installer-mysql-no-java-ubuntu-1204>.
------Exception-------
Class: Kitchen::ActionFailed
Message: SSH exited (1) for command: [sudo -E chef-solo --config /tmp/kitchen/solo.rb --json-attributes /tmp/kitchen/dna.json  --log_level info]
---Nested Exception---
Class: Kitchen::SSHFailed
Message: SSH exited (1) for command: [sudo -E chef-solo --config /tmp/kitchen/solo.rb --json-attributes /tmp/kitchen/dna.json  --log_level info]
------Backtrace-------
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:112:in `rescue in run_remote'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:108:in `run_remote'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:48:in `block in converge'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/ssh.rb:47:in `initialize'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:43:in `new'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:43:in `converge'
/Users/my_user_name/.gem/ruby/1.9.3/gems/kitchen-vagrant-0.14.0/lib/kitchen/driver/vagrant.rb:75:in `converge'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `public_send'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `block in perform_action'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `call'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `synchronize_or_call'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:283:in `block in action'
/Users/my_user_name/.rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:282:in `action'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `perform_action'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:256:in `converge_action'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:246:in `block in transition_to'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `each'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `transition_to'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:141:in `verify'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:170:in `block in test'
/Users/my_user_name/.rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:166:in `test'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `public_send'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `block (2 levels) in run_action'
/Users/my_user_name/.gem/ruby/1.9.3/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/Users/my_user_name/.gem/ruby/1.9.3/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
----------------------
``````

**Comment by esciara** [comment]
The case is handled in `templates/default/setenv.sh.erb`:

```
<% if node['java'] && node['java']['java_home'] -%>
JRE_HOME="<%= node['java']['java_home'] %>/jre/"; export JRE_HOME
<% else -%>
JRE_HOME="<%= node['confluence']['install_path'] %>/jre/"; export JRE_HOME
<% end -%>
```

but not in `recipes/linux_installer.rb` as shown in the log.

**Comment by legal90** [comment]
Fixed with GH-32
