### ISSUE TITLE
Cookbook fails when using java cookbook

### ISSUE THREAD

**Issue by esciara** [sous-chefs/confluence#8]
On 7ed6eef7d6ad859ec13cc55d527316dbbd7f1bcf with `bundle exec kitchen test -mysql-ubuntu-1204`.

Backtrace:

```
Recipe: java::set_java_home[0m
  * ruby_block[set-env-java-home] action run[0m[2014-04-11T19:13:46+00:00] INFO: Processing ruby_block[set-env-java-home] action run (java::set_java_home line 19)
[2014-04-11T19:13:46+00:00] INFO: ruby_block[set-env-java-home] called
[32m
    - execute the ruby block set-env-java-home[0m
[0m
  * directory[/etc/profile.d] action create[0m[2014-04-11T19:13:46+00:00] INFO: Processing directory[/etc/profile.d] action create (java::set_java_home line 26)
 (up to date)[0m
  * file[/etc/profile.d/jdk.sh] action create[0m[2014-04-11T19:13:46+00:00] INFO: Processing file[/etc/profile.d/jdk.sh] action create (java::set_java_home line 30)
[2014-04-11T19:13:46+00:00] INFO: file[/etc/profile.d/jdk.sh] created file /etc/profile.d/jdk.sh
[32m
    - create new file /etc/profile.d/jdk.sh[0m[2014-04-11T19:13:46+00:00] INFO: file[/etc/profile.d/jdk.sh] updated file contents /etc/profile.d/jdk.sh
[32m
    - update content in file /etc/profile.d/jdk.sh from none to 58a2aa[0m[37m
        --- /etc/profile.d/jdk.sh   2014-04-11 19:13:46.231437218 +0000[0m[37m
        +++ /tmp/.jdk.sh20140411-1243-cq9jzk    2014-04-11 19:13:46.231437218 +0000[0m[37m
        @@ -1 +1,2 @@[0m[37m
        +export JAVA_HOME=/usr/lib/jvm/java-7-oracle[0m[2014-04-11T19:13:46+00:00] INFO: file[/etc/profile.d/jdk.sh] mode changed to 755
[32m
    - change mode from '' to '0755'[0m
[0m
Recipe: java::oracle[0m
  * java_ark[jdk] action install[0m[2014-04-11T19:13:46+00:00] INFO: Processing java_ark[jdk] action install (java::oracle line 53)
[2014-04-11T19:13:46+00:00] INFO: Adding jdk to /usr/lib/jvm/jdk1.7.0_51
[32m
    - create dir /usr/lib/jvm and change owner to root[0mRecipe: <Dynamically Defined Resource>[0m
  * package[curl] action install[0m[2014-04-11T19:13:46+00:00] INFO: Processing package[curl] action install (/tmp/kitchen/cookbooks/java/providers/ark.rb line 72)
[32m
    - install version 7.22.0-3ubuntu4.7 of package curl[0m
[0m
[0m
================================================================================[0m
[31mError executing action `install` on resource 'java_ark[jdk]'[0m
================================================================================[0m

[0m
Mixlib::ShellOut::ShellCommandFailed[0m
------------------------------------[0m
Expected process to exit with [0], but received '18'
---- Begin output of  curl --create-dirs -L --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz -o /tmp/kitchen/cache/jdk-7u51-linux-x64.tar.gz  ----
STDOUT: 
STDERR: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

  0  131M    0  536k    0     0   188k      0  0:11:54  0:00:02  0:11:52  188k
  1  131M    1 1451k    0     0   377k      0  0:05:57  0:00:03  0:05:54  913k
  1  131M    1 2113k    0     0   436k      0  0:05:09  0:00:04  0:05:05  788k
  2  131M    2 3162k    0     0   541k      0  0:04:09  0:00:05  0:04:04  875k
  3  131M    3 4096k    0     0   591k      0  0:03:48  0:00:06  0:03:42  871k
  3  131M    3 4096k    0     0   591k      0  0:03:48  0:00:06  0:03:42  871k
curl: (18) transfer closed with 134005386 bytes remaining to read

---- End output of  curl --create-dirs -L --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz -o /tmp/kitchen/cache/jdk-7u51-linux-x64.tar.gz  ----
Ran  curl --create-dirs -L --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz -o /tmp/kitchen/cache/jdk-7u51-linux-x64.tar.gz  returned 18[0m

[0m
Cookbook Trace:[0m

---------------[0m
/tmp/kitchen/cookbooks/java/providers/ark.rb:81:in `block in download_direct_from_oracle'
/tmp/kitchen/cookbooks/java/providers/ark.rb:78:in `download_direct_from_oracle'
/tmp/kitchen/cookbooks/java/providers/ark.rb:119:in `block in class_from_file'[0m

[0m
Resource Declaration:[0m

---------------------[0m

# In /tmp/kitchen/cookbooks/java/recipes/oracle.rb


 53: java_ark "jdk" do
 54:   url tarball_url
 55:   default node['java']['set_default']
 56:   checksum tarball_checksum
 57:   app_home java_home
 58:   bin_cmds bin_cmds
 59:   alternatives_priority 1062
 60:   action :install
 61: end
 62: 
[0m

[0m
Compiled Resource:[0m

------------------[0m

# Declared in /tmp/kitchen/cookbooks/java/recipes/oracle.rb:53:in `from_file'

java_ark("jdk") do
  action [:install]
  supports {:report=>true, :exception=>true}
  retries 0
  retry_delay 2
  guard_interpreter :default
  cookbook_name :java
  recipe_name "oracle"
  url "http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz"
  default true
  checksum "764f96c4b078b80adaa5983e75470ff2"
  app_home "/usr/lib/jvm/java-7-oracle"
  bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jhat", "jinfo", "jmap", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
  alternatives_priority 1062
  owner "root"
  app_home_mode 493
end
[0m

[0m
[2014-04-11T19:13:56+00:00] INFO: Running queued delayed notifications before re-raising exception


Running handlers:[0m
[2014-04-11T19:13:56+00:00] ERROR: Running exception handlers
Running handlers complete
[0m
[2014-04-11T19:13:56+00:00] ERROR: Exception handlers complete

[2014-04-11T19:13:56+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
Chef Client failed. 11 resources updated in 82.719693942 seconds[0m
[2014-04-11T19:13:56+00:00] ERROR: java_ark[jdk] (java::oracle line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '18'
---- Begin output of  curl --create-dirs -L --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz -o /tmp/kitchen/cache/jdk-7u51-linux-x64.tar.gz  ----
STDOUT: 
STDERR: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

  0  131M    0  536k    0     0   188k      0  0:11:54  0:00:02  0:11:52  188k
  1  131M    1 1451k    0     0   377k      0  0:05:57  0:00:03  0:05:54  913k
  1  131M    1 2113k    0     0   436k      0  0:05:09  0:00:04  0:05:05  788k
  2  131M    2 3162k    0     0   541k      0  0:04:09  0:00:05  0:04:04  875k
  3  131M    3 4096k    0     0   591k      0  0:03:48  0:00:06  0:03:42  871k
  3  131M    3 4096k    0     0   591k      0  0:03:48  0:00:06  0:03:42  871k
curl: (18) transfer closed with 134005386 bytes remaining to read
---- End output of  curl --create-dirs -L --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz -o /tmp/kitchen/cache/jdk-7u51-linux-x64.tar.gz  ----
Ran  curl --create-dirs -L --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz -o /tmp/kitchen/cache/jdk-7u51-linux-x64.tar.gz  returned 18
[2014-04-11T19:13:56+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Converge failed on instance <confluence-installer-mysql-ubuntu-1204>.
------Exception-------
Class: Kitchen::ActionFailed
Message: SSH exited (1) for command: [sudo -E chef-solo --config /tmp/kitchen/solo.rb --json-attributes /tmp/kitchen/dna.json  --log_level info]
---Nested Exception---
Class: Kitchen::SSHFailed
Message: SSH exited (1) for command: [sudo -E chef-solo --config /tmp/kitchen/solo.rb --json-attributes /tmp/kitchen/dna.json  --log_level info]
------Backtrace-------
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:112:in `rescue in run_remote'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:108:in `run_remote'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:48:in `block in converge'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/ssh.rb:47:in `initialize'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:43:in `new'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:43:in `converge'
/Users/my_user_name/.gem/ruby/1.9.3/gems/kitchen-vagrant-0.14.0/lib/kitchen/driver/vagrant.rb:75:in `converge'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `public_send'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `block in perform_action'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `call'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `synchronize_or_call'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:283:in `block in action'
/Users/my_user_name/.rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:282:in `action'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `perform_action'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:256:in `converge_action'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:246:in `block in transition_to'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `each'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `transition_to'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:141:in `verify'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:170:in `block in test'
/Users/my_user_name/.rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:166:in `test'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `public_send'
/Users/my_user_name/.gem/ruby/1.9.3/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `block (2 levels) in run_action'
/Users/my_user_name/.gem/ruby/1.9.3/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/Users/my_user_name/.gem/ruby/1.9.3/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
----------------------
```

**Comment by esciara** [comment]
Looks like it is an Oracle issue... socrata-cookbooks/java#161

**Comment by legal90** [comment]
Yep, it is not related to the cookbook.
